# Generated by Django 3.1.3 on 2020-11-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201112_1615'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Student',
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Horror Stories', 'Horror Stories'), ('Fairy Tales', 'Fairy Tales'), ('Mysterious', 'Mysterious'), ('Comedy', 'Comedy'), ('Tragedy', 'Tragedy')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Returned', 'Returned'), ('Have To Return', 'Have To Return')], max_length=200, null=True),
        ),
    ]
